### ISSUE TITLE
Impossibile End Editing

### ISSUE THREAD

**Issue by Piero87** [zoonooz/ZFTokenField#3]
Hi, this library is amazing, i have found for now only one bug, i can't end editing, because the delegate method end editing return always NO, how i can achieve this?

**Comment by zoonooz** [comment]
Thanks @Piero87 , the bug end editing you mean hide keyboard ?

**Comment by Piero87** [comment]
Yes :)

**Comment by zoonooz** [comment]
You can use delegate `- (BOOL)tokenFieldShouldEndEditing:(ZFTokenField *)textField` and return whether you want to end editing or not. Every time when you call `reloadData`, tokenField will ask for that.

The reason is when you call `reloadData` the textField inside tokenField will temporary remove and re-add to the tokenField which somehow UIKit resign first responder from our textField. And that makes textFieldShouldEndEditing get called every time.

If you want to dismiss keyboard now you can do that in two way (I can think of)
1. User hit return button and you return YES in above delegate.
2. You dismiss by code using `[self.view endEditing:YES]` or `[tokenField.textField resignFirstResponder]`, these methods will also trigger above delegate so you might need some flag to indicate that it will return YES in case of these methods.

**Comment by Piero87** [comment]
thanks

**Comment by zoonooz** [comment]
I have edited previous comment FYI. :)
